name: Samsung SM8150 a826xq Kernel Build

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: "Checkout kernel source"
        uses: actions/checkout@v4    

      - name: "Set up build environment"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential bc bison flex make git curl wget cpio zip unzip rsync kmod pv lz4 xz-utils \
            zlib1g-dev libssl-dev libelf-dev libncurses-dev libtool automake autoconf pkg-config uuid-dev \
            liblz4-dev openssl python3 python-is-python3 python3-pip p7zip-full gcc g++ clang lld \
            erofs-utils f2fs-tools fuse2fs fuse3 libfuse3-dev attr device-tree-compiler android-sdk-libsparse-utils openjdk-17-jdk

          wget https://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2_amd64.deb
          sudo dpkg -i libtinfo5_6.3-2_amd64.deb
          sudo apt-get install -f -y

      - name: "Download Toolchain & Setup KernelSU-Next"
        run: |
          # 1. Download the Samsung CFP GCC toolchain archive
          wget -O gcc-cfp.tar.gz https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/gcc-cfp-jopp-only.tar.gz
          
          # 2. Extract the archive
          tar -xvf gcc-cfp.tar.gz

          # 3. Move the extracted toolchain into the precise directory structure your build script expects
          mkdir -p toolchain/gcc-cfp/gcc-cfp-single
          mv gcc-cfp/gcc-cfp-jopp-only/aarch64-linux-android-4.9 toolchain/gcc-cfp/gcc-cfp-single/

          # 4. Setup KernelSU-Next using the legacy branch (recommended for Android 4.9 kernels)
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s legacy

      - name: "Setting permission"
        run: chmod +x build_kernel.sh

      - name: "Build for specific device"
        run: ./build_kernel.sh
